apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec2
spec:
  selector:
    matchLabels:
      app: ec2
  replicas: 1
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::200650688734:role/ec2-list
      labels:
        app: ec2
    spec:
      containers:
      - name: app
        image: yago/aws-sdk
        env:
        - name: AWS_REGION
          value: "us-east-1"
