apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec2
spec:
  selector:
    matchLabels:
      app: ec2
  replicas: 1
  template:
    metadata:
      labels:
        app: ec2
    spec:
      containers:
      - name: app
        image: yago/aws-sdk2
        env:
        - name: AWS_REGION
          value: "us-east-1"
